### ISSUE TITLE
error processing --userid: strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by florian-obradovic** [pieterclaerhout/export-komoot#10]
Hi,
thanks a lot for all the work you put into this :)

I'm trying to get it running but I get this error:
```
make run-full
Usage: export-komoot [--email EMAIL] [--password PASSWORD] [--userid USERID] [--filter FILTER] [--format FORMAT] [--to TO] [--fulldownload] [--concurrency CONCURRENCY] [--tourtype TOURTYPE]
error: error processing --userid: strconv.ParseInt: parsing "": invalid syntax
make: *** [run-full] Error 255
```

.env:
```
KOMOOT_EMAIL=my@email
KOMOOT_PASSWD=my_Password
KOMOOT_USERID=123456789999
```
Any idea?

Thank you very much and best regards, Flo.

**Comment by pieterclaerhout** [comment]
Hi Flo,

this is due to the fact that the readme was not updated properly.

The error you are getting is because the parameter "--userid" is missing from the command line.

It should be specified and contain your Komoot user ID.

To find your Komoot user ID, login to Komoot, click on your user name in the upper right corner of the screen and
select the option "Profile". The URL you will navigate to will look like this:

```
https://www.komoot.com/<lang>>-<localle>/user/<userid>
```

Your user ID is the number in the last part of the URL.

I've updated the readme to contain this and also updated the parsing of the CLI arguments so that you get a more descriptive error message.

**Comment by florian-obradovic** [comment]
Hi @pieterclaerhout 
thanks a lot.

I still have issues getting it running "No tours need to be downloaded". Any hint?

```
 ./export-komoot --email my@email  --password MyPassword --userid 123456789999 --format gpx --to ./tours --fulldownload
2025-03-22 22:54:13.485 | INFO  | Exporting: my@email
2025-03-22 22:54:13.486 | INFO  |        to: /Users/flo/Downloads/export-komoot/tours
2025-03-22 22:54:13.486 | INFO  |    format: gpx
2025-03-22 22:54:13.486 | INFO  | Komoot User ID: 123456789999
2025-03-22 22:54:14.005 | INFO  | No tours need to be downloaded
2025-03-22 22:54:14.005 | INFO  | Elapsed: 519.254959ms
```

thanks and best regards, Flo.

**Comment by pieterclaerhout** [comment]
Can you try again with the latest version?

The latest version now exports both planned and recorded tours (which I'm guessing is the problem here).

**Comment by florian-obradovic** [comment]
Works  ❤️
Is there a limit for 1500 tours?
```
2025-03-24 07:35:00.553 | INFO  | Downloaded 1500 tours
2025-03-24 07:35:00.556 | INFO  | Saving tour list
2025-03-24 07:35:00.586 | INFO  | Saving parsed tour list
2025-03-24 07:35:00.588 | INFO  | Elapsed: 13.611342875s
```

**Comment by pieterclaerhout** [comment]
At the moment, yes, the upper limit is 1500 tours. How many do you have in total?

**Comment by pieterclaerhout** [comment]
Thinking of it, you might want to try with changing it in `komoot/tours.go` line 14.

It might be though that Komoot imposes an upper limit, but it's worth a try.

**Comment by florian-obradovic** [comment]
Works
```
2025-03-24 09:06:33.567 | INFO  | Downloaded 3180 tours
2025-03-24 09:06:33.571 | INFO  | Saving tour list
2025-03-24 09:06:33.617 | INFO  | Saving parsed tour list
2025-03-24 09:06:33.621 | INFO  | Elapsed: 26.404995209s
```
